### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by Ads20000** [abigail-m/lol-unpackman#1]
I put `unpackman.cpp` in `drive_c/Riot Games/League of Legends/RADS/solutions/lol_game_client_sln/releases/0.0.1.228/deploy` then `g++ -o Leagueoflinux unpackman.cpp` and `./Leagueoflinux`

```
Segmentation fault (core dumped)
```

```
$ journalctl -f
Leagueoflinux[8222]: segfault at 7f82339c4fc8 ip 00005613b6c6fd59 sp 00007ffeaa033e20 error 4 in Leagueoflinux[5613b6c6f000+2000]
```

Using `g++ -W -Wall -pedantic -o Leagueoflinux -p unpackman.cpp`

I get the following which may or may not be helpful:

```
unpackman.cpp: In function ‘void ReadFile(const char*, const char*, uint8_t**, int*)’:
unpackman.cpp:89:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (fread(*out, 1, *len, f) != *len) {
      ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~`
```

Note: I'm only running this to try and get League to run on Ubuntu.

Ubuntu 18.04 on Linux 4.15.0-29-generic

**Comment by DirkyJerky** [comment]
I believe this is because you are not using the correct default binary, It is irrelevant now anyways as the build is now 0.0.1.230 and the binary layout has changed.

**Comment by Ads20000** [comment]
Has anyone updated the script for 0.0.1.230 or is that not possible?

**Comment by abigail-m** [comment]
This is a bit useless as they have updated anyway. 

I wouldn't recommend you use this to play League on linux. You'll get banned pretty fast as this is probably detected the same as any other hack tool.

Use this tool to create a binary for static analysis in something like IDA.

Run it again in GDB if you really are still interested in fixing it and get back to me. Get more info on the crash.

**Comment by abigail-m** [comment]
>Has anyone updated the script for 0.0.1.230 or is that not possible?

Possibly when I get home to have a look.

**Comment by Ads20000** [comment]
> You'll get banned pretty fast as this is probably detected the same as any other hack tool.

Hence using a smurf... to be fair, League are still thinking about how to best help Wine to get it to work on Linux, so perhaps I should be patient with them on that...

```
$ gdb Leagueoflinux
$ run
Program received signal SIGSEGV, Segmentation fault.
0x0000555555554c13 in Decrypt(GKey*, void const*, void*, unsigned long) ()
```

I haven't tried doing this before (I'm not a programmer) but what other info do you need from gdb? :)

**Comment by DirkyJerky** [comment]
This unpacker specifically actually allows League to work under wine properly. To make the Riot-provided decryption/anti-cheat tool work under wine properly is a very different ballgame.

https://bugs.winehq.org/show_bug.cgi?id=45327 is where the discussion is somewhat centralized.

**Comment by abigail-m** [comment]
thanks

**Comment by dvtate** [comment]
![image](https://user-images.githubusercontent.com/15305612/43353184-6b327e86-91ff-11e8-8bb6-8b85c9f36213.png)

**Comment by abigail-m** [comment]
You can talk to me on discord if you want more info abigail#4412
